steps:
# Build the container image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: sh
  args: [
    '-c', 'git lfs pull'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${SHORT_SHA}', '.', '--target', 'production']
  env:
    - 'DOCKER_BUILDKIT=1'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '${_APP_NAME}-${_ENV}',
    '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA',
    '--region', 'asia-northeast1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--update-secrets=MC_CHIMERA_LINE_ACCESS_TOKEN=MC_CHIMERA_LINE_ACCESS_TOKEN:latest,MC_CHIMERA_LINE_CHANNEL_SECRET=MC_CHIMERA_LINE_CHANNEL_SECRET:latest'
    ]

substitutions:
  _APP_NAME: 'mc-chimera'
  _ENV: 'dev'

timeout: 3600s

