version: '3.3'
services:
  mc_chimera:
    build:
      context: .
      target: development
    ports:
      - "18001:18001"
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    tty: true
    stdin_open: true
    command: >
      bash -c "uvicorn --host 0.0.0.0 --port 18001 --reload mc_chimera.main:app"

